In [2]:
import numpy as np
import matplotlib.pyplot as pl
import random
%matplotlib inline


In [6]:
###GENERA LOS VALORES DE X y Y
x= np.random.randint(0,10,size=[5,5])
print(x)
y= np.random.randint(0,10,size=[5,5])
print(y)

[[6 2 6 3 3]
 [7 6 8 1 8]
 [1 9 8 1 4]
 [0 2 8 6 7]
 [2 7 5 0 0]]
[[9 6 0 8 6]
 [8 3 0 5 0]
 [7 2 3 3 1]
 [0 7 3 1 3]
 [0 2 1 6 9]]


In [ ]:
##INGRESA LAS FILAS Y COLUMNAS##
row=int(input('Ingrese cantidad de filas'))
col=int(input('Ingrese cantidad de columnas'))

##INGRESA JOINVECT Y SE VERIFICA SI LA DISTRIBUCION ES CORRECTA...FALTAA
join = input('Ingrese distribucion de grafico')
t_joinvect = np.array([(1,3),4,5,6,(7,9)])

## INGRESA EL TIPO DE GRAFICO
TdeGraf=[]
for i in range(0,5):
    num =input('Ingrese Tipo de Grafico del Grafico Numero (%d): ' % (i))
    TdeGraf.append(num)
print(TdeGraf)

## INGRESA LOS XLIM YLIM
xlim =[]
ylim = []
for i in range(5):
    numx = [int(input('Ingrese limite inferior de x (%d):'% (i))),int(input('Ingrese limite superior de x (%d):' % (i)))]
    numy = [int(input('Ingrese limite inferior de y (%d):' % (i))),int(input('Ingrese limite superior de y (%d):'% (i)))]
    xlim.append(numx)
    ylim.append(numy)
print(xlim)
print(xlim)

## SE INGRESA LOS XLABEL YLABEL
xlabel =[]
ylabel = []
for i in range(5):
    j=input('Ingrese Nombre del EjeX del Grafico Numero (%d): ' % (i))
    p=input('Ingrese Nombre del EjeY del Grafico Numero (%d): ' % (i))
    xlabel.append(j)
    ylabel.append(p)
print(xlabel)
print(ylabel)

###SE INGRESA LOS NUMPLOT
numplot=[]
for i in range(5):
    num =int(input('Ingrese numero del plot del Grafico Numero (%d):' % (i)))
    numplot.append(num)
print(numplot)


show=True


if(show):
        pl.figure(figsize=[10,10])
        for i in range(5):
            if(TdeGraf[i]=='stem'):
                pl.subplot(row,col,t_joinvect[i])
                pl.stem(x[i],y[i],markerfmt='C1o')
                #pl.plot(x[i],y[i])
                pl.ylabel(xlabel[i])
                pl.xlabel(ylabel[i])
                pl.xlim(xlim[i])
                pl.ylim(ylim[i])
                pl.title(numplot[i])
            else:
                pl.subplot(row,col,t_joinvect[i])
                pl.plot(x[i],y[i])
                pl.ylabel(xlabel[i])
                pl.xlabel(ylabel[i])
                pl.xlim(xlim[i])
                pl.ylim(ylim[i])
                pl.title(numplot[i])
        
        
        pl.show()
    


In [ ]:
txt = "hello, my name is Peter, I am 26 years old"

x = txt.split(", ")

print(x)

In [10]:
join1=[]
join2=[]
y=[]
z=[]
for i in range(2):
      join = input('Ingrese distribucion de grafico')
      x=join.split("-")
      join1.append(x)
print(join1)
print(join1[0])
for j in range(2):
      join2=join1[j]
      b=[int(x) for x in join2]
      y.extend(b)
      z.append(b)        
  
print(join2)
print(b)
print(y)
print(y[0])
if len(y)!=len(set(y)):
    print('hay')
if(max(y)>9):
    print('hh')




Ingrese distribucion de grafico 10
Ingrese distribucion de grafico 10


[['10'], ['10']]
['10']
['10']
[10]
[10, 10]
10
hay
hh


In [ ]:
a=['1','2','3','4']

b= [int(x) for x in a]

print(b)

In [17]:
myList = [1,5,9,5,1,9] 

myList = list(set(myList)) 

print(myList)
print(len(myList))
 

[1, 5, 9]
3


In [9]:
def contarElementosLista(lista):
    """
    Recibe una lista, y devuelve un diccionario con todas las repeticiones de
    cada valor
    """
    map={i:lista.count(i) for i in lista}  
    print(map)
    return {i:lista.count(i) for i in lista}
 
lista = ["a", "c", "b", "a", "c", "c", "a", "c"]
resultado=contarElementosLista(lista) # {'a': 3, 'b': 1, 'c': 3}
maximo=max(resultado, key=resultado.get)
print("El valor mas repetido es el ",maximo," con ",resultado[maximo]," veces")
 
 
lista = [1,2,3,2,1,4,2,5,2,4,2,3]
resultado=contarElementosLista(lista) # {1: 2, 2: 5, 3: 2, 4: 2, 5: 1}
maximo=max(resultado, key=resultado.get)
print("El valor mas repetido es el ",maximo," con ",resultado[maximo]," veces")

{'a': 3, 'c': 4, 'b': 1}
El valor mas repetido es el  c  con  4  veces
{1: 2, 2: 5, 3: 2, 4: 2, 5: 1}
El valor mas repetido es el  2  con  5  veces


In [12]:
lista=[-1,2,1,1,3,9,5,55]
if len(lista)==len(set(lista)): # False porque hay dos '1'
    print ('no se solapan graficos')
print(max(lista))
print(min(lista))
    

55
-1
