# Comentarios

In [2]:
# Primeros comandos de Python
# Comentarios de una sola linea
"""
Comentarios multilinea
Comentarios multilinea
"""

'\nComentarios multilinea\nComentarios multilinea\n'

# Importando librerías

In [3]:
import numpy as np
import matplotlib.pyplot as plt

# Asignaciones basicas

In [4]:
d_num  = 5
d_flt  = 5.
d_str  = 'texto'
d_numv = [0,1,2,3]
d_strv = ['Sol','Luna','Tierra']

# Imprimir en pantalla

In [5]:
print('#############################################')
print('Este numero es: ',d_num)
print(d_str)
print('Lista: ',d_numv,'\t','Un dato: ',d_numv[0])
print('Lista: ',d_strv,'\t','Un dato: ',d_strv[2])
print('El valor d_strv: %s'%d_strv[0])
print('El valor d_strv: %.2f'%(12.5555))
print('El valor d_strv: {:.2f}'.format(12.5555))
print('#############################################')

#############################################
Este numero es:  5
texto
Lista:  [0, 1, 2, 3] 	 Un dato:  0
Lista:  ['Sol', 'Luna', 'Tierra'] 	 Un dato:  Tierra
El valor d_strv: Sol
El valor d_strv: 12.56
El valor d_strv: 12.56
#############################################


# Operaciones

In [6]:
print('#############################################')
suma     = 3 + d_num;    print('Sum:',suma)
resta    = suma - 15;    print('Res:',resta)
prod     = suma * resta; print('Pro:',prod)
div      = 6/2;          print('Div:',div,'\tTipo:',type(div))
div_e    = 6//2;         print('Div entera:',div_e,'\tTipo:',type(div_e))
modulo   = 8 % 3;        print('Mod:',modulo)
strv     = 'day'*2;      print(strv)        # Se repite la palabra
lists    = d_numv * 3;   print(lists)       # Se repite la lista
print('#############################################')

#############################################
Sum: 8
Res: -7
Pro: -56
Div: 3.0 	Tipo: <class 'float'>
Div entera: 3 	Tipo: <class 'int'>
Mod: 2
dayday
[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
#############################################


# Condicional y métodos de generación de strings

In [7]:
print ('#############################################')
ptr = 0
if(ptr==0):
    print ("Este numero es %d"%ptr)
elif(ptr==1):
    print ("Este numero es %d"%ptr + " no esperado")
elif(ptr>20 and ptr<=30):
    print ('>>>>>>>: ',ptr )
else:
    print ('El valor es %d %s'%(ptr,"no esperado"))
print ('#############################################')

#############################################
Este numero es 0
#############################################


# Iterativo

In [8]:
print ('#############################################')
for ptr in range(8):
    print (ptr,end=' ')
print()
print ('#############################################')

#############################################
0 1 2 3 4 5 6 7 
#############################################


# Operaciones con vectores (np.ndarray)

In [9]:
print('#############################################')
t_array = np.array([0,1,2,3]);                   print(t_array)
t_array = np.arange(0,5,2);                      print(t_array) 
t_array = np.arange(0,5)*3;                      print(t_array)
t_array = np.arange(0,5)//3;                     print(t_array)
t_array = np.arange(0,5)/3;                      print(t_array)
t_array = np.arange(0,5)*np.arange(0,5);         print(t_array)
t_array = np.dot(np.arange(0,5),np.arange(0,5)); print(t_array)

t_matrix = np.dot(np.matrix([[0, 1, 2, 3],[0, 1, 2, 3]]),
                  np.matrix([[0, 1], [2, 3],[0, 1], [2, 3]])); print(t_matrix)
print(type(t_matrix))
print('#############################################')

#############################################
[0 1 2 3]
[0 2 4]
[ 0  3  6  9 12]
[0 0 0 1 1]
[0.         0.33333333 0.66666667 1.         1.33333333]
[ 0  1  4  9 16]
30
[[ 8 14]
 [ 8 14]]
<class 'numpy.matrix'>
#############################################


# Seleccion en vectores

In [10]:
print ('#############################################')
t0     = np.arange(0,5);                        print (t0)

t0[0]  = 25;                                    print (t0)                          
t0[-1] = 45;                                    print (t0)                          
t0[:]  = 1;                                     print (t0)
t0[0:2]= 3;                                     print (t0)
t0[3:5]= 2;                                     print (t0)
t0[0:6]= 5;                                     print (t0)

t0     = np.arange(0,5);                        print (t0)
c0= t0>2;                                       print (c0)
t1 = t0[c0];                                    print (t1)
t2 = t0[t0<=2];                                 print (t2)

print (len(t0),'\n',np.size(t0),'\n',np.size(t_matrix))
print (np.shape(t_matrix))
print ('#############################################')

#############################################
[0 1 2 3 4]
[25  1  2  3  4]
[25  1  2  3 45]
[1 1 1 1 1]
[3 3 1 1 1]
[3 3 1 2 2]
[5 5 5 5 5]
[0 1 2 3 4]
[False False False  True  True]
[3 4]
[0 1 2]
5 
 5 
 4
(2, 2)
#############################################


# Matrices

In [9]:
print ('#############################################')
t1         = np.zeros((1,5)); print (t1)
print(type(t1))
t1         = np.ones((3,5)) ; print (t1)
t1         = np.zeros((5,5)); print (t1)

t1[:,3]    = 1;               print (t1)
t1[0:5:2,:2]  = 2;            print (t1)
t1         = t1 + 5;          print (t1)
t1         = t1 - 5;          print (t1)
t1         = t1 * 5;          print (t1)
t1         = t1 / 5;          print (t1)
t2         = t1 * t1;         print (t2)
t2         = np.dot(t1, t1);  print (t2)
r,c=np.shape(t1);             print (r,c)
print ('#############################################')

#############################################
[[0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]
[[2. 2. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [2. 2. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [2. 2. 0. 1. 0.]]
[[7. 7. 5. 6. 5.]
 [5. 5. 5. 6. 5.]
 [7. 7. 5. 6. 5.]
 [5. 5. 5. 6. 5.]
 [7. 7. 5. 6. 5.]]
[[2. 2. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [2. 2. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [2. 2. 0. 1. 0.]]
[[10. 10.  0.  5.  0.]
 [ 0.  0.  0.  5.  0.]
 [10. 10.  0.  5.  0.]
 [ 0.  0.  0.  5.  0.]
 [10. 10.  0.  5.  0.]]
[[2. 2. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [2. 2. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [2. 2. 0. 1. 0.]]
[[4. 4. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [4. 4. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [4. 4. 0. 1. 0.]]
[[4. 4. 0. 5. 0.]
 [0. 0. 0. 1. 0.]
 [4. 4. 0. 5. 0.]
 [0. 0. 0. 1. 0.]
 [4. 4. 0. 5. 0.]]
5 5
########

# Iterativo

In [12]:
print ('#############################################')
t_vec = np.arange(0.,25.1,1.)
print (t_vec)
for ptr in range(len(t_vec)-1,-1,-1):
    print (t_vec[ptr])
print ('#############################################')

#############################################
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25.]
25.0
24.0
23.0
22.0
21.0
20.0
19.0
18.0
17.0
16.0
15.0
14.0
13.0
12.0
11.0
10.0
9.0
8.0
7.0
6.0
5.0
4.0
3.0
2.0
1.0
0.0
#############################################


## Ejemplo

In [13]:
print('#############################################')
count = 0
lista = []
for ptr in t_vec[0:5]:
    print (ptr)
    count += 1
    t_vec[count]=ptr+2
    lista.append(ptr+2)
print("Vec>> ",t_vec[1:6])
print("List>> ",lista)
print('#############################################')

#############################################
0.0
2.0
4.0
6.0
8.0
Vec>>  [ 2.  4.  6.  8. 10.]
List>>  [2.0, 4.0, 6.0, 8.0, 10.0]
#############################################


## Iterativo

In [14]:
print('#############################################')
ptr = 0
o_data = 0
while(ptr < len(t_vec)):
    o_data += t_vec[ptr]
    ptr    += 1
print(o_data)
print('#############################################')

#############################################
340.0
#############################################


# Igualdad en float

In [1]:
a=2/3.1
b=0.2/0.31
print (a==b)

False


In [2]:
print(a)
print(b)

0.6451612903225806
0.6451612903225807


In [ ]:
print('{:.22f}'.format(a))
print('{:.22f}'.format(b))

In [ ]:
def are_equal(n1,n2):
    return abs(n1-n2)<0.0000001

print(are_equal(a,b))

In [ ]:
import math
print(math.isclose(a, b, abs_tol=0.0000001))

# Definicion de funciones

In [ ]:
def producto(a,b):
    c = a * b
    return c

c = producto(2,2)
print (c)

## Pasaje de argumentos mutables e inmutables

In [ ]:
def funcion(val):
    val=4
    print(val)
    return

x=10
funcion(x)
print(x)

In [ ]:
def funcion2 (lista):
    lista.append(40)
    #lista[0] = 8
    #lista = [8]
    #print(lista)
    return

x=[10,20,30]
funcion2(x)
print(x)

In [ ]:
def funcion3 (vector):
    vector[0] = 8
    #vector = np.array([8])
    #print(vector)
    return

x=np.array([10,20,30])
funcion3(x)
print(x)

# Shallow copy - Deep copy

In [ ]:
colores1 = ["rojo", "azul"]
colores2 = colores1
print(colores1)
print(colores2)

In [ ]:
colores2[0]="amarillo"
print(colores1)
print(colores2)

In [ ]:
colores1 = ["rojo", "azul"]
colores2 = colores1

colores2=["amarillo","verde"]
print(colores1)
print(colores2)

In [ ]:
colores1 = ["rojo", "azul"]
colores2 = colores1[:]

colores2[0]="amarillo"
print(colores1)
print(colores2)

In [ ]:
colores1 = ["rojo", "azul"]
colores2 = colores1.copy()

colores2[0]="amarillo"
print(colores1)
print(colores2)

In [ ]:
#Con vectores

numeros1 = np.arange(0,4)
numeros2 = numeros1
numeros2[0:2] = 33
print(numeros1)
print(numeros2)

numeros1 = np.arange(0,4)
numeros2 = numeros1.copy() #deep copy
numeros2[0:2] = 33
print(numeros1)
print(numeros2)

# Importando módulos

In [1]:
import sys
print(sys.path)

['C:\\Users\\silvi\\Documents\\Python Scripts\\Clase 1', 'C:\\Users\\silvi\\anaconda3\\python37.zip', 'C:\\Users\\silvi\\anaconda3\\DLLs', 'C:\\Users\\silvi\\anaconda3\\lib', 'C:\\Users\\silvi\\anaconda3', '', 'C:\\Users\\silvi\\anaconda3\\lib\\site-packages', 'C:\\Users\\silvi\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\silvi\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\silvi\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\silvi\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\silvi\\.ipython']


In [2]:
import hola
hola.decirHola("Juan")

Hola Juan!


# Entrada de datos

In [ ]:
a = input('Ingrese Opcion')
print (a)